services:
  - type: web
    name: wiki-quiz-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        scope: run
      - key: GOOGLE_API_KEY
        scope: run
